{{/* Code generated by agentio-chart-sync. DO NOT EDIT. */}}
{{/* Per-image registry > Agentio registry > chart registry > Docker Hub.
Qualified repositories retain their host. Digests take precedence over tags. */}}
{{- define "agentio.registryImage" -}}
{{- $parentImage := .root.Values.image | default dict -}}
{{- $registry := .image.registry | default .globalRegistry | default $parentImage.registry | default "docker.io" -}}
{{- $repository := required "Agentio image.repository is required" .image.repository -}}
{{- $host := first (splitList "/" $repository) -}}
{{- if not (or (contains "." $host) (contains ":" $host) (eq $host "localhost")) -}}
{{- $repository = printf "%s/%s" (trimSuffix "/" $registry) $repository -}}
{{- end -}}
{{- if .image.digest -}}
{{- printf "%s@%s" $repository .image.digest -}}
{{- else -}}
{{- printf "%s:%s" $repository (required "Agentio image.tag is required without a digest" (.image.tag | default .defaultTag)) -}}
{{- end -}}
{{- end -}}
