apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sandbox-manager.fullname" . }}
  labels:
    {{- include "sandbox-manager.labels" . | nindent 4 }}
  {{- with .Values.sandboxManager.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.sandboxManager.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - "*.{{ .Values.sandboxManager.e2b.domain }}"
        - "{{ .Values.sandboxManager.e2b.domain }}"
      secretName: "{{ .Values.sandboxManager.ingress.certSecretName }}"
  rules:
    - host: '*.{{ .Values.sandboxManager.e2b.domain }}'
      http:
        paths:
          - backend:
              service:
                name: {{ include "sandbox-manager.fullname" . }}
                port:
                  number: 8080
            path: /sandboxes
            pathType: Prefix
          - backend:
              service:
                name: {{ include "sandbox-manager.fullname" . }}
                port:
                  number: 8080
            path: /v2/sandboxes
            pathType: Prefix
          - backend:
              service:
                name: {{ include "sandbox-manager.fullname" . }}
                port:
                  number: 7788
            path: /
            pathType: Prefix
    - host: {{ .Values.sandboxManager.e2b.domain }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "sandbox-manager.fullname" . }}
                port:
                  number: 8080
            path: /kruise/api
            pathType: Prefix
          - backend:
              service:
                name: {{ include "sandbox-manager.fullname" . }}
                port:
                  number: 7788
            path: /
            pathType: Prefix
