apiVersion: v1
kind: Secret
metadata:
  name: e2b-key-store
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "sandbox-manager.labels" . | nindent 4 }}
type: Opaque
data: { }