{{/* Code generated by agentio-chart-sync. DO NOT EDIT. */}}
{{- define "agentio.config" }}
{{- if .Values.agentio.epe.enabled }}
sandboxExtProc:
  service: {{ .Values.agentio.epe.name }}.{{ include "agentio.namespace" . }}.svc.cluster.local
  port: {{ .Values.agentio.epe.port }}
  messageTimeout: {{ default "5s" .Values.agentio.epe.messageTimeout }}
  request:
    headerMode: SEND
    attributes:
    - filter_state['sandbox.id']
    - filter_state['sandbox.token']
    - filter_state['sandbox.labels']
    - filter_state['downstream_peer'].name
    - filter_state['downstream_peer'].namespace
    - destination.port
    - source.address
  response:
    headerMode: SKIP
{{- end }}
{{- if .Values.agentio.egressPolicies }}
egressPolicies:
{{ toYaml .Values.agentio.egressPolicies }}
{{- end }}
{{- end }}
