{{/* Code generated by agentio-chart-sync. DO NOT EDIT. */}}
{{- define "agentio.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" -}}
{{- end -}}



{{- define "agentio.gatewayDeployerEnabled" -}}
{{- eq .Values.agentio.egressGateway.mode "gatewayAPI" -}}
{{- end -}}

{{- define "agentio.epeEnabled" -}}
{{- ne .Values.agentio.epe.mode "disabled" -}}
{{- end -}}

{{- define "agentio.epeService" -}}
{{- if eq .Values.agentio.epe.mode "managed" -}}
{{- printf "%s.%s.svc.%s" (include "agentio.epe.fullname" .) (include "agentio.namespace" .) .Values.agentio.global.clusterDomain -}}
{{- else if eq .Values.agentio.epe.mode "external" -}}
{{- .Values.agentio.epe.external.address -}}
{{- end -}}
{{- end -}}

{{- define "agentio.epePort" -}}
{{- if eq .Values.agentio.epe.mode "managed" -}}
{{- .Values.agentio.epe.service.grpcPort -}}
{{- else if eq .Values.agentio.epe.mode "external" -}}
{{- .Values.agentio.epe.external.port -}}
{{- end -}}
{{- end -}}

{{- define "agentio.epeAddress" -}}
{{- if ne .Values.agentio.epe.mode "disabled" -}}
{{- printf "%s:%v" (include "agentio.epeService" .) (include "agentio.epePort" .) -}}
{{- end -}}
{{- end -}}

{{- define "agentio.validate" -}}
{{- if and (eq .Values.agentio.egressGateway.mode "gatewayAPI") .Values.agentio.egressGateway.gatewayAPI.create -}}
{{- if empty .Values.agentio.egressGateway.gatewayAPI.name -}}
{{- fail "egressGateway.gatewayAPI.name is required when mode=gatewayAPI and create=true" -}}
{{- end -}}
{{- if empty .Values.agentio.egressGateway.gatewayAPI.gatewayClassName -}}
{{- fail "egressGateway.gatewayAPI.gatewayClassName is required when mode=gatewayAPI and create=true" -}}
{{- end -}}
{{- if empty .Values.agentio.egressGateway.gatewayAPI.listeners -}}
{{- fail "egressGateway.gatewayAPI.listeners must contain at least one listener when mode=gatewayAPI and create=true" -}}
{{- end -}}
{{- end -}}
{{- if eq .Values.agentio.epe.mode "managed" -}}
{{- $source := .Values.agentio.epe.credentialProvider.mtls.source -}}
{{- if not (has $source (list "files" "secret" "none")) -}}
{{- fail (printf "epe.credentialProvider.mtls.source must be files, secret, or none; got %q" $source) -}}
{{- end -}}
{{- if and (eq $source "secret") (or (empty .Values.agentio.epe.credentialProvider.mtls.secret.namespace) (empty .Values.agentio.epe.credentialProvider.mtls.secret.name)) -}}
{{- fail "epe.credentialProvider.mtls.secret.namespace and name are required when source=secret" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "agentio.agentiod.name" -}}
{{- default "agentiod" .Values.agentio.agentiod.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "agentio.agentiod.fullname" -}}
{{- default (include "agentio.agentiod.name" .) .Values.agentio.agentiod.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "agentio.agentiod.labels" -}}
helm.sh/chart: {{ include "agentio.chart" . }}
app.kubernetes.io/name: {{ include "agentio.agentiod.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: agentio
app.kubernetes.io/component: control-plane
{{- end -}}

{{- define "agentio.agentiod.selectorLabels" -}}
app.kubernetes.io/name: {{ include "agentio.agentiod.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}

{{- define "agentio.agentiod.serviceAccountName" -}}
{{- default (include "agentio.agentiod.fullname" .) .Values.agentio.agentiod.serviceAccount.name -}}
{{- end -}}

{{- define "agentio.agentiod.image" -}}
{{- include "agentio.registryImage" (dict "root" . "image" .Values.agentio.agentiod.image "globalRegistry" .Values.agentio.global.registry "defaultTag" .Values.agentio.global.tag) -}}
{{- end -}}





{{- define "agentio.agentiod.caConfigMapName" -}}
{{- default .Values.agentio.global.caCertConfigMap .Values.agentio.agentiod.ca.configMapName -}}
{{- end -}}
















{{- define "agentio.gateway.name" -}}{{ default "agentio-egress" .Values.agentio.egressGateway.nameOverride | trunc 63 | trimSuffix "-" }}{{- end -}}
{{- define "agentio.gateway.fullname" -}}{{ default (include "agentio.gateway.name" .) .Values.agentio.egressGateway.fullnameOverride | trunc 63 | trimSuffix "-" }}{{- end -}}
{{- define "agentio.gateway.serviceAccountName" -}}{{ default (include "agentio.gateway.fullname" .) .Values.agentio.egressGateway.serviceAccount.name }}{{- end -}}
{{- define "agentio.gateway.image" -}}
{{- include "agentio.registryImage" (dict "root" . "image" .Values.agentio.egressGateway.image "globalRegistry" .Values.agentio.global.registry "defaultTag" .Values.agentio.global.tag) -}}
{{- end -}}
{{- define "agentio.gateway.xdsAddress" -}}{{ printf "%s.%s.svc.%s:15012" (include "agentio.agentiod.fullname" .) (include "agentio.namespace" .) .Values.agentio.global.clusterDomain }}{{- end -}}
{{- define "agentio.gateway.epeAddress" -}}{{ include "agentio.epeAddress" . }}{{- end -}}
{{- define "agentio.gateway.labels" -}}
helm.sh/chart: {{ include "agentio.chart" . }}
app.kubernetes.io/name: {{ include "agentio.gateway.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: agentio
app.kubernetes.io/component: egress-gateway
networking.agents.kruise.io/sandbox-egress: "true"
gateway.networking.k8s.io/gateway-name: {{ include "agentio.gateway.fullname" . }}
{{- end -}}
{{- define "agentio.gateway.selectorLabels" -}}
gateway.networking.k8s.io/gateway-name: {{ include "agentio.gateway.fullname" . }}
networking.agents.kruise.io/sandbox-egress: "true"
{{- end -}}

{{- define "agentio.epe.name" -}}{{ default "agentio-epe" .Values.agentio.epe.nameOverride | trunc 63 | trimSuffix "-" }}{{- end -}}
{{- define "agentio.epe.fullname" -}}{{ default (include "agentio.epe.name" .) .Values.agentio.epe.fullnameOverride | trunc 63 | trimSuffix "-" }}{{- end -}}
{{- define "agentio.epe.serviceAccountName" -}}{{ default (include "agentio.epe.fullname" .) .Values.agentio.epe.serviceAccount.name }}{{- end -}}
{{- define "agentio.epe.image" -}}
{{- include "agentio.registryImage" (dict "root" . "image" .Values.agentio.epe.image "globalRegistry" .Values.agentio.global.registry "defaultTag" .Values.agentio.global.tag) -}}
{{- end -}}
{{- define "agentio.epe.mtlsSecretName" -}}{{ default (printf "%s-mtls-client-cert" (include "agentio.epe.fullname" .)) .Values.agentio.epe.credentialProvider.mtls.secretName }}{{- end -}}
{{- define "agentio.epe.labels" -}}
helm.sh/chart: {{ include "agentio.chart" . }}
app.kubernetes.io/name: {{ include "agentio.epe.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: agentio
app.kubernetes.io/component: extproc
{{- end -}}
{{- define "agentio.epe.selectorLabels" -}}
app.kubernetes.io/name: {{ include "agentio.epe.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
