{{/* Code generated by agentio-chart-exporter. DO NOT EDIT. */}}
{{/*
Shared helpers for the agentio chart.
*/}}

{{/* Namespace for all agentio resources: the Helm release namespace. */}}
{{- define "agentio.namespace" -}}
{{ .Release.Namespace }}
{{- end -}}

{{/*
Common labels
*/}}

{{/* Chart name and version for the helm.sh/chart label. */}}
{{- define "agentio.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* Provenance labels applied to every rendered resource's metadata (never to selectors). */}}
{{- define "agentio.commonLabels" -}}
helm.sh/chart: {{ include "agentio.chart" . }}
app.kubernetes.io/part-of: agentio
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end -}}

{{/* CA certificate ConfigMap name. */}}
{{- define "agentio.caCertConfigMap" -}}
{{ .Values.agentio.global.caCertConfigMap }}
{{- end -}}

{{/* agentiod (control plane) deployment name. */}}
{{- define "agentio.controller.name" -}}
agentiod
{{- end -}}

{{/* Metadata labels for control-plane (agentiod) resources. Not a selector. */}}
{{- define "agentio.controller.labels" -}}
app: {{ include "agentio.controller.name" . }}
{{ include "agentio.commonLabels" . }}
{{- end -}}

{{/* Ambient mode toggle. */}}
{{- define "agentio.ambient.enabled" -}}
{{- .Values.agentio.ambient.enabled -}}
{{- end -}}

{{/*
Image helpers
*/}}

{{/* Construct a full image reference: hub/name:tag with global.hub fallback. */}}
{{- define "agentio.image" -}}
{{- $hub := .hub | default .globalHub -}}
{{- printf "%s/%s:%s" $hub .name .tag -}}
{{- end -}}

{{/* Ztunnel image (shared by sidecar injection and ambient DaemonSet). */}}
{{- define "agentio.ztunnelImage" -}}
{{- include "agentio.image" (dict "hub" .Values.agentio.ztunnel.image.hub "name" .Values.agentio.ztunnel.image.name "tag" .Values.agentio.ztunnel.image.tag "globalHub" .Values.agentio.global.hub) -}}
{{- end -}}

{{/* Lightweight image used by the iptables init container. */}}
{{- define "agentio.proxyInitImage" -}}
{{- include "agentio.image" (dict "hub" .Values.agentio.proxyInit.image.hub "name" .Values.agentio.proxyInit.image.name "tag" .Values.agentio.proxyInit.image.tag "globalHub" .Values.agentio.global.hub) -}}
{{- end -}}

{{/*
CNI helpers
*/}}

{{- define "agentio.cni.name" -}}
agentio-cni
{{- end -}}

{{- define "agentio.cni.daemonsetName" -}}
agentio-cni-node
{{- end -}}

{{- define "agentio.cni.configName" -}}
agentio-cni-config
{{- end -}}

{{- define "agentio.cni.selectorLabels" -}}
k8s-app: {{ include "agentio.cni.daemonsetName" . }}
{{- end -}}

{{- define "agentio.cni.labels" -}}
{{ include "agentio.cni.selectorLabels" . }}
app: {{ include "agentio.cni.name" . }}
{{ include "agentio.commonLabels" . }}
{{- end -}}

{{/*
Ztunnel helpers
*/}}

{{- define "agentio.ztunnel.name" -}}
ztunnel
{{- end -}}

{{- define "agentio.ztunnel.selectorLabels" -}}
app: {{ include "agentio.ztunnel.name" . }}
{{- end -}}

{{- define "agentio.ztunnel.labels" -}}
{{ include "agentio.ztunnel.selectorLabels" . }}
{{ include "agentio.commonLabels" . }}
{{- end -}}
