apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sandbox-controller.fullname" . }}
  namespace: {{ include "sandbox-controller.namespace" . }}
  labels:
    {{- include "sandbox-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sandbox-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sandbox-controller.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sandbox-controller.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            - --leader-elect
            - --health-probe-bind-address=:{{ .Values.healthProbe.port }}
            - --webhook-cert-path=/home/nonroot/sandbox-controller-webhook-certs
          command:
            - /manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.healthProbe.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports: [ ]
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.healthProbe.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: webhook-certs
              mountPath: /home/nonroot/sandbox-controller-webhook-certs
        {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: webhook-certs
          emptyDir: { }
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              control-plane: {{ include "sandbox-controller.name" . }}
{{- if and ( eq (int .Capabilities.KubeVersion.Major) 1) ( gt (int .Capabilities.KubeVersion.Minor) 26 ) }}
          matchLabelKeys:
            - pod-template-hash
{{- end }}
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
