apiVersion: v1
kind: Service
metadata:
  name: sandbox-controller-manager-webhook-service
  namespace: {{ include "sandbox-controller.namespace" . }}
  labels:
    {{- include "sandbox-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "sandbox-controller.selectorLabels" . | nindent 4 }}
