
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.installation.namespace }}-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Values.installation.namespace }}-webhook-service
        namespace: {{ .Values.installation.namespace }}
        path: /mutate-unified-workload
    failurePolicy: Fail
    name: munifiedworload.kb.io
    objectSelector:
      matchExpressions:
        - key: rollouts.kruise.io/workload-type
          operator: Exists
    rules:
      - apiGroups:
          - '*'
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Values.installation.namespace }}-webhook-service
        namespace: {{ .Values.installation.namespace }}
        path: /mutate-apps-v1-deployment
    failurePolicy: Fail
    name: mdeployment.kb.io
    objectSelector:
      matchExpressions:
        - key: control-plane
          operator: NotIn
          values:
            - controller-manager
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - UPDATE
        resources:
          - deployments
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Values.installation.namespace }}-webhook-service
        namespace: {{ .Values.installation.namespace }}
        path: /mutate-apps-kruise-io-v1alpha1-cloneset
    failurePolicy: Fail
    name: mcloneset.kb.io
    rules:
      - apiGroups:
          - apps.kruise.io
        apiVersions:
          - v1alpha1
        operations:
          - UPDATE
        resources:
          - clonesets
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Values.installation.namespace }}-webhook-service
        namespace: {{ .Values.installation.namespace }}
        path: /mutate-apps-v1-statefulset
    failurePolicy: Fail
    name: mstatefulset.kb.io
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - UPDATE
        resources:
          - statefulsets
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Values.installation.namespace }}-webhook-service
        namespace: {{ .Values.installation.namespace }}
        path: /mutate-apps-kruise-io-statefulset
    failurePolicy: Fail
    name: madvancedstatefulset.kb.io
    rules:
      - apiGroups:
          - apps.kruise.io
        apiVersions:
          - v1alpha1
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - statefulsets
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: {{ .Values.installation.namespace }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Values.installation.namespace }}-webhook-service
        namespace: {{ .Values.installation.namespace }}
        path: /validate-rollouts-kruise-io-rollout
    failurePolicy: Fail
    name: vrollout.kb.io
    rules:
      - apiGroups:
          - rollouts.kruise.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rollouts
    sideEffects: None
