apiVersion: v1
name: kruise
description: Helm chart for kruise components
version: 1.0.1
appVersion: 1.0.1
kubeVersion: ">= 1.16.0-0"
icon: https://openkruise.io/img/openkruise-logo-bg.jpg
keywords:
  - openkruise
  - kubernetes
  - kruise
  - workload
  - statefulset
  - sidecar
  - job
  - deployment
  - cloneset
home: https://openkruise.io
sources:
  - https://github.com/openkruise/kruise
annotations:
  artifacthub.io/changes: |
    - "[Changed]: https://github.com/openkruise/kruise/blob/master/CHANGELOG.md"
