apiVersion: v1
name: kruise
description: Helm chart for kruise components
version: 0.10.0
icon: https://openkruise.io/img/logo_white.png
keywords:
  - openkruise
  - kubernetes
  - kruise
  - workload
  - statefulset
  - sidecar
  - job
  - deployment
  - cloneset
home: https://openkruise.io
sources:
  - https://github.com/openkruise/kruise
