apiVersion: v1
kind: Service
metadata:
  name: {{ include "kruise-state-metrics.fullname" . }}
  namespace: {{ .Values.installation.namespace }}
  labels:
    {{- include "kruise-state-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
    - name: telemetry
      port: 8081
      targetPort: telemetry
  selector:
    {{- include "kruise-state-metrics.selectorLabels" . | nindent 4 }}
