{{- if .Values.sidecarInjector.enabled }}
apiVersion: v1
data:
  config: |-
    # defaultTemplates defines the default template to use for pods that do not explicitly specify a template
    defaultTemplates: [ztunnel]
    policy: enabled
    alwaysInjectSelector:
      []
    neverInjectSelector:
      []
    injectedAnnotations:
    template: {{ `{{ Template_Version_And_Istio_Version_Mismatched_Check_Installation }}` | quote }}
    templates:
      ztunnel: |
{{ .Files.Get "files/ztunnel-injection-template.yaml" | trim | indent 8 }}
      waypoint: |
{{ .Files.Get "files/waypoint-injection-template.yaml" | trim | indent 8 }}
  values: |-
    {
      "gateways": {
        "seccompProfile": {},
        "securityContext": {}
      },
      "global": {
        "proxy_ztunnel": {
          "image": "{{ include "agentio.ztunnelImage" . }}",
          "enableFirewallRules": {{ .Values.global.enableFirewallRules | default false }},
          "firewallBackend": "{{ .Values.sidecarInjector.ztunnel.firewallBackend | default "auto" }}"
        },
        "caAddress": "{{ include "agentio.controller.name" . }}.{{ include "agentio.namespace" . }}.svc.cluster.local:15012",
        "xdsAddress": "{{ include "agentio.controller.name" . }}.{{ include "agentio.namespace" . }}.svc.cluster.local:15012",
        "trustBundleName": "{{ include "agentio.caCertConfigMap" . }}",
        "caName": "",
        "certSigners": [],
        "configCluster": false,
        "configValidation": true,
        "defaultPodDisruptionBudget": {
          "enabled": true
        },
        "defaultResources": {
          "requests": {
            "cpu": "10m"
          }
        },
        "externalIstiod": false,
        "hub": "{{ .Values.global.hub }}",
        "imagePullPolicy": "",
        "imagePullSecrets": [],
        "istioNamespace": "{{ include "agentio.namespace" . }}",
        "istiod": {
          "enableAnalysis": false
        },
        "logAsJson": false,
        "logging": {
          "level": "default:info"
        },
        "meshID": "",
        "meshNetworks": {},
        "mountMtlsCerts": false,
        "multiCluster": {
          "clusterName": "{{ .Values.global.clusterId }}"
        },
        "nativeNftables": false,
        "network": "",
        "networkPolicy": {
          "enabled": false
        },
        "omitSidecarInjectorConfigMap": false,
        "operatorManageWebhooks": false,
        "pilotCertProvider": "istiod",
        "priorityClassName": "",
        "proxy": {
          "image": "{{ .Values.proxy.image.hub | default .Values.global.hub }}/{{ .Values.proxy.image.name }}:{{ .Values.proxy.image.tag }}",
          "autoInject": "enabled",
          "clusterDomain": "{{ .Values.global.trustDomain }}",
          "componentLogLevel": "misc:error",
          "excludeIPRanges": "",
          "excludeInboundPorts": "",
          "excludeOutboundPorts": "",
          "includeIPRanges": "*",
          "includeInboundPorts": "*",
          "includeOutboundPorts": "",
          "logLevel": "warning",
          "outlierLogPath": "",
          "privileged": false,
          "readinessFailureThreshold": 4,
          "readinessInitialDelaySeconds": 0,
          "readinessPeriodSeconds": 15,
          "resources": {
            "limits": {
              "cpu": "2000m",
              "memory": "1024Mi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "seccompProfile": {},
          "startupProbe": {
            "enabled": true,
            "failureThreshold": 600
          },
          "statusPort": 15020,
          "tracer": "none"
        },
        "proxy_init": {
          "forceApplyIptables": false,
          "image": "{{ include "agentio.proxyInitImage" . }}"
        },
        "remotePilotAddress": "",
        "resourceScope": "all",
        "sds": {
          "token": {
            "aud": "istio-ca"
          }
        },
        "sts": {
          "servicePort": 0
        },
        "tag": "{{ .Values.proxy.image.tag }}",
        "variant": "distroless",
        "waypoint": {
          "affinity": {},
          "nodeSelector": {},
          "resources": {
            "limits": {
              "cpu": "2",
              "memory": "1Gi"
            },
            "requests": {
              "cpu": "100m",
              "memory": "128Mi"
            }
          },
          "tolerations": [],
          "topologySpreadConstraints": []
        }
      },
      "pilot": {
        "cni": {
          "ambient": {
            "enabled": true
          },
          "provider": "default"
        },
        "env": {
          "PILOT_ENABLE_AMBIENT": "true"{{- if .Values.global.enableClusterTrustBundle }},
          "ENABLE_CLUSTER_TRUST_BUNDLE_API": true{{- end }}{{- if .Values.sniTrafficPolicy.enabled }},
          "ENABLE_SNI_TRAFFIC_POLICY": true,
          "POLICY_STORE_REFERENCE_RESOLUTION_GRACE_PERIOD": {{ .Values.policyRuntime.referenceResolutionGracePeriod | default "15s" | quote }}{{- end }}
        }
      },
      "revision": "",
      "sidecarInjectorWebhook": {
        "alwaysInjectSelector": [],
        "defaultTemplates": [],
        "enableNamespacesByDefault": false,
        "injectedAnnotations": {},
        "neverInjectSelector": [],
        "reinvocationPolicy": "Never",
        "rewriteAppHTTPProbe": true,
        "templates": {}
      }
    }
kind: ConfigMap
metadata:
  name: {{ .Values.global.resourcePrefix }}-sidecar-injector
  namespace: {{ include "agentio.namespace" . }}
  labels:
    app: sidecar-injector
    {{- include "agentio.commonLabels" . | nindent 4 }}
{{- end }}
