apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "agentio.controller.labels" . | nindent 4 }}
  name: {{ include "agentio.controller.name" . }}
  namespace: {{ include "agentio.namespace" . }}
