{{- if .Values.ambient.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "agentio.ztunnel.labels" . | nindent 4 }}
  name: {{ include "agentio.ztunnel.name" . }}
  namespace: {{ include "agentio.namespace" . }}
{{- end }}
