{{/* Code generated by agentio-chart-sync. DO NOT EDIT. */}}
{{/*
Shared helpers for the agentio chart.
*/}}

{{/* Namespace for all Agentio resources. */}}
{{- define "agentio.namespace" -}}
{{ .Values.agentio.global.namespace | default "agentio-system" }}
{{- end -}}

{{/*
Common labels
*/}}

{{/* Chart name and version for the helm.sh/chart label. */}}
{{- define "agentio.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/* Provenance labels applied to every rendered resource's metadata (never to selectors). */}}
{{- define "agentio.commonLabels" -}}
helm.sh/chart: {{ include "agentio.chart" . }}
app.kubernetes.io/part-of: agentio
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end -}}

{{/* CA certificate ConfigMap name. */}}
{{- define "agentio.caCertConfigMap" -}}
{{ .Values.agentio.global.caCertConfigMap }}
{{- end -}}

{{/* agentiod (control plane) deployment name. */}}
{{- define "agentio.controller.name" -}}
agentiod
{{- end -}}

{{/* Metadata labels for control-plane (agentiod) resources. Not a selector. */}}
{{- define "agentio.controller.labels" -}}
app: {{ include "agentio.controller.name" . }}
{{ include "agentio.commonLabels" . }}
{{- end -}}

{{/* Ambient mode toggle. */}}
{{- define "agentio.ambient.enabled" -}}
{{- .Values.agentio.ambient.enabled -}}
{{- end -}}

{{/*
Image helpers
*/}}

{{/* Construct a full image reference: hub/name:tag with global.hub fallback. */}}
{{- define "agentio.image" -}}
{{- $hub := .hub | default .globalHub -}}
{{- printf "%s/%s:%s" $hub .name .tag -}}
{{- end -}}

{{/* Ztunnel image (shared by sidecar injection and ambient DaemonSet). */}}
{{- define "agentio.ztunnelImage" -}}
{{- include "agentio.image" (dict "hub" .Values.agentio.ztunnel.image.hub "name" .Values.agentio.ztunnel.image.name "tag" .Values.agentio.ztunnel.image.tag "globalHub" .Values.agentio.global.hub) -}}
{{- end -}}

{{/* Lightweight image used by the iptables init container. */}}
{{- define "agentio.proxyInitImage" -}}
{{- include "agentio.image" (dict "hub" .Values.agentio.proxyInit.image.hub "name" .Values.agentio.proxyInit.image.name "tag" .Values.agentio.proxyInit.image.tag "globalHub" .Values.agentio.global.hub) -}}
{{- end -}}

{{/*
CNI helpers
*/}}

{{- define "agentio.cni.name" -}}
agentio-cni
{{- end -}}

{{- define "agentio.cni.daemonsetName" -}}
agentio-cni-node
{{- end -}}

{{- define "agentio.cni.configName" -}}
agentio-cni-config
{{- end -}}

{{- define "agentio.cni.selectorLabels" -}}
k8s-app: {{ include "agentio.cni.daemonsetName" . }}
{{- end -}}

{{- define "agentio.cni.labels" -}}
{{ include "agentio.cni.selectorLabels" . }}
app: {{ include "agentio.cni.name" . }}
{{ include "agentio.commonLabels" . }}
{{- end -}}

{{/*
EPE credential-provider mTLS helpers
*/}}

{{/*
The credential-provider mTLS source that will actually take effect.

epe.env is rendered after the chart's own env entries, so a key set there wins
at runtime. Both the validation below and the conditional rendering in epe.yaml
resolve the source through this helper so they agree with what the container
will really see — otherwise setting the source via epe.env would trip the
validation or mount the wrong volume.
*/}}
{{- define "agentio.epe.credProviderMtlsSource" -}}
{{- $env := .Values.agentio.epe.env | default dict -}}
{{- $typed := .Values.agentio.epe.credentialProvider.mtls.source | default "files" -}}
{{- get $env "CREDENTIAL_PROVIDER_MTLS_SOURCE" | default $typed -}}
{{- end -}}

{{/*
Fail rendering on a credential-provider mTLS configuration the process would
reject at startup, so the feedback arrives from `helm template` rather than
from a CrashLoopBackOff.

Mirrors credProviderFor in extensions/epe/pkg/wiring/credprovider.go: an
unrecognized source is a startup error, and so is source=secret without both a
namespace and a name. Absent or unusable *material* is deliberately NOT checked
here — that is a valid degraded mode, not a misconfiguration.
*/}}
{{- define "agentio.epe.validateCredProviderMtls" -}}
{{- $env := .Values.agentio.epe.env | default dict -}}
{{- $mtls := .Values.agentio.epe.credentialProvider.mtls -}}
{{- $source := include "agentio.epe.credProviderMtlsSource" . -}}
{{- if not (has $source (list "files" "secret" "none")) -}}
{{- fail (printf "epe.credentialProvider.mtls.source must be one of \"files\", \"secret\", or \"none\", got %q" $source) -}}
{{- end -}}
{{- if eq $source "secret" -}}
{{- $ns := $mtls.secret.namespace | default (get $env "CREDENTIAL_PROVIDER_SECRET_NAMESPACE") -}}
{{- $name := $mtls.secret.name | default (get $env "CREDENTIAL_PROVIDER_SECRET_NAME") -}}
{{- if not $ns -}}
{{- fail "epe.credentialProvider.mtls.source=secret requires epe.credentialProvider.mtls.secret.namespace (or CREDENTIAL_PROVIDER_SECRET_NAMESPACE in epe.env)" -}}
{{- end -}}
{{- if not $name -}}
{{- fail "epe.credentialProvider.mtls.source=secret requires epe.credentialProvider.mtls.secret.name (or CREDENTIAL_PROVIDER_SECRET_NAME in epe.env)" -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/* Secret backing the source=files mount. The chart does not create it. */}}
{{- define "agentio.epe.credProviderMtlsFilesSecretName" -}}
{{- .Values.agentio.epe.credentialProvider.mtls.secretName | default (printf "%s-mtls-client-cert" .Values.agentio.epe.name) -}}
{{- end -}}

{{/*
Ztunnel helpers
*/}}

{{- define "agentio.ztunnel.name" -}}
ztunnel
{{- end -}}

{{- define "agentio.ztunnel.selectorLabels" -}}
app: {{ include "agentio.ztunnel.name" . }}
{{- end -}}

{{- define "agentio.ztunnel.labels" -}}
{{ include "agentio.ztunnel.selectorLabels" . }}
{{ include "agentio.commonLabels" . }}
{{- end -}}

{{/* Render a CRD with a Helm policy that preserves it during uninstall. */}}
{{- define "agentio.renderCRD" -}}
{{- $keepPolicy := dict "metadata" (dict "annotations" (dict "helm.sh/resource-policy" "keep")) -}}
{{- mergeOverwrite (. | fromYaml) $keepPolicy | toYaml -}}
{{- end -}}
