name: E2E-base

on:
  push:
    branches:
      - master
      - release-*
  pull_request: { }
  workflow_dispatch: { }

# Declare default permissions as read only.
permissions: read-all

env:
  # Common versions
  GO_VERSION: '1.22'
  KIND_VERSION: 'v0.18.0'
  KIND_VERSION_FOR_HIGHER: 'v0.22.0'
  KIND_CLUSTER_NAME: 'ci-testing'
# todo: add kruise e2e here
jobs:
  # 1.27-
  install-for-lower:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kind-version: [ v1.18.20, v1.20.15, v1.24.6, v1.26.3 ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Setup Kind Cluster ${{ matrix.kind-version }}
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          node_image: kindest/node:${{ matrix.kind-version }}
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
          config: ./test/kind-conf.yaml
          version: ${{ env.KIND_VERSION }}
      - name: Install Kruise
        run: |
          make install-kruise-from-local
      - name: install Kruise state metrics
        run: |
          make install-kruise-state-metrics-from-local
      - name: install Kruise rollout
        if: ${{ ! startsWith(matrix.kind-version, 'v1.18') }}
        run: |
            make install-kruise-rollout-from-local
      - name: install Kruise game
        run: |
          make install-kruise-game-from-local

  # 1.27+
  install-for-higher:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kind-version: [ v1.28.7, v1.30.8 ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Setup Kind Cluster ${{ matrix.kind-version }}
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          node_image: kindest/node:${{ matrix.kind-version }}
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
          config: ./test/kind-conf-with-vpa.yaml
          version: ${{ env.KIND_VERSION_FOR_HIGHER }}
      - name: Install Kruise
        run: |
          make install-kruise-from-local
      - name: install Kruise state metrics
        run: |
          make install-kruise-state-metrics-from-local
      - name: install Kruise rollout
        run: |
          make install-kruise-rollout-from-local
      - name: install Kruise game
        run: |
          make install-kruise-game-from-local
